### ISSUE TITLE
Fingerprint setup

### ISSUE THREAD

**Issue by vsrnth** [thape-cn/oauth2id#13]
In `saml_idp.rb`
```
config.x509_certificate = Rails.application.credentials.oauth2id_x509_certificate!

service_providers = {
    "https://saml-example.test/saml/metadata" => {
      fingerprint: Rails.application.credentials.oauth2id_x509_sha256_fingerprint!,
```

Is the fingerprint based on the `Rails.application.credentials.oauth2id_x509_certificate!`?

**Comment by vsrnth** [comment]
I apologize for the multiple issues I've opened; just looking at the codebase while trying to implement something similar

**Comment by Eric-Guo** [comment]
yes, you need to generate your own x509 certificate, [readme mentioned](https://github.com/thape-cn/oauth2id#saml-20), but PR for improvement are very welcome.
