### ISSUE TITLE
First user register problem

### ISSUE THREAD

**Issue by qichunren** [thape-cn/oauth2id#28]
Failed to register first user.

ENV:
* Ruby 3.2.2
* OS: Ubuntu 22.04

Steps:

1. git clone
2. bundle
3. rails db:migrate
4. rails s
5. Open http://127.0.0.1:3000/users/sign_up, fill register form, submit.

![image](https://github.com/thape-cn/oauth2id/assets/39784/e531329e-f845-4a6d-a160-ab4d8c9f5f3e)

If export RAILS_MASTER_KEY env before start rails server, the result error is: 
```
SQLite3::ConstraintException: NOT NULL constraint failed: allowlisted_jwts.aud
```
![1703473801154](https://github.com/thape-cn/oauth2id/assets/39784/ebf60ffe-dd61-4e59-8682-f0a06d21c2df)

**Comment by Eric-Guo** [comment]
I agree it's a 500 error, but https://github.com/thape-cn/oauth2id#first-user-is-admin
